language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
script:
  - bash -ex .travis-ocaml.sh
  - cp ./dot_ocamlinit $HOME/.ocamlinit
  - opam install -y oasis
  - make
env:
  - OCAML_VERSION=4.02
os:
  - linux
notifications:
  email:
    - reximkut@gmail.com
